name: "Trigger GitLab CI Job"
description: "Triggering GitLab CI Job through the API"
author: "Bo-Yi Wu"
inputs:
  host:
    description: "gitlab-ci base url"
    default: "https://gitlab.com"
  token:
    description: "gitlab-ci token"
    required: true
  ref:
    description: "gitlab-ci valid refs are only the branches and tags"
    default: "main"
  project_id:
    description: "gitlab project id"
    required: true
  insecure:
    description: "insecure mode"
  variables:
    description: "pass CI/CD variables"
  debug:
    description: "debug mode"
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check-circle"
  color: "orange"
